# Site settings
title: David Laing
email: davidkendalllaing@gmail.com
url: "https://davidklaing.com" # the base hostname & protocol for your site
twitter_username: davidklaing
github_username:  davidklaing

# Build settings
markdown: kramdown

plugins: 
  - jekyll-twitter-plugin
